[feat] Multisig single signer functions
ferrumnet/quantum-portal-smart-contracts pull request #10
Opened 2022-12-29 12:48 UTC by 3ierratango

Changelog:
- Adds functions for single signer to approve Multisig
Depends on https://github.com/ferrumnet/foundry-contracts/pull/8

2023-01-11 09:04 UTC, naiemk requested changes

2023-01-11 09:04 UTC, naiemk commented on contracts/quantumPortal/poc/poa/QuantumPortalAuthorityMgr.sol
> +                alreadySigned[completedSigners[i]] = false;
delete alreadySigned[completedSigners[i]];
This will save gas

2023-01-11 09:04 UTC, naiemk commented on package.json
> +    "foundry-contracts": "git+https://github.com/3ierratango/foundry-contracts#multisig-multiple",
dont push this. We will merge the dependency first

2023-01-11 09:04 UTC, naiemk commented on test/quantumPortal/poc/QuantumPortalUtils.ts
> +import { abi, deployWithOwner, expiryInFuture, getCtx, isAllZero, Salt, TestContext, ZeroAddress} from
Move back to foundry-contract

2023-01-11 09:04 UTC, naiemk commented on test/quantumPortal/poc/QuantumPortalUtils.ts
> +import { getBridgeMethodCall } from '../../bridge/BridgeUtilsV12';
same

2023-01-12 10:18 UTC, 3ierratango commented on test/quantumPortal/poc/QuantumPortalUtils.ts
> +import { getBridgeMethodCall } from '../../bridge/BridgeUtilsV12';
Done, need https://github.com/ferrumnet/foundry-contracts/pull/9 to unblock

2023-01-12 10:18 UTC, 3ierratango commented on package.json
> +    "foundry-contracts": "git+https://github.com/3ierratango/foundry-contracts#multisig-multiple",
will wait for https://github.com/ferrumnet/foundry-contracts/pull/8

2023-01-18 19:03 UTC, naiemk approved these changes

2023-01-18 19:06 UTC, naiemk commented
Please resolve the conflict

2023-01-18 19:19 UTC, naiemk requested changes

2023-01-18 19:19 UTC, naiemk commented on contracts/quantumPortal/poc/poa/QuantumPortalAuthorityMgr.sol
> +        address signer = validateSignature(message, 1, signature);
Instead use the following code:

```
// Validate the message for only this signer
bytes32        digest = _hashTypedDataV4(message);
(bool result, address[] memory signers) = tryVerifyDigestWithAddressWithMinSigCheck(digest, 1, signature, false);
require(result, "QPAM: Invalid signer");
require(signers.length == 1, "QPAM: Wrong number of signers");
address signer = signers[0];
```

2023-01-31 23:59 UTC, naiemk approved these changes

2023-02-01 20:53 UTC, merged